baseURL = "https://armoghan-blogs.netlify.app/"
canonifyURLs=true
pluralizeListTitles = false
summaryLength   = 25

languageCode  = "en-us"
title         = "Armoghan"

disqusShortname = ""

[params]
    description     = "The Ultimate Tech Blogging Theme"
    contactEmail    = "Armoghan@proton.me"
    footer          = ""
    googleSearch    = "google-cse-key"
    googleAnalytics = ""      # Google Analytics v4
    adsense         = "pub-2047325115998150"
    math            = false   # best to enable this in the front matter of a page
    mermaid         = false   # best to enable this in the front matter of a page

    # Social Media Params
    facebook   = "https://www.facebook.com/armoghanul.mohmin"
    twitter    = "https://twitter.com/Armoghan12"
    youtube    = ""
    instagram  = "https://www.instagram.com/___armoghan/"
    github     = "https://github.com/Armoghan-ul-Mohmin"
    pinterest  = ""
    linkedin   = "http://www.linkedin.com/in/armoghan-ul-mohmin-4289a9248"


# Configure the site menu here
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        weight = 2
            [[menu.main]]
                name = "Posts"
                url = "/posts/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "Sections"
                url = "/sections/"
                weight = 2
            [[menu.main]]
                parent = "blog"
                name = "divider"
                weight = 3
            [[menu.main]]
                parent = "blog"
                name = "Tags"
                url = "/tags/"
                weight = 4
            [[menu.main]]
                parent = "blog"
                name = "Cheat Sheets"
                url = "/cheatsheets/"
                weight = 5
    [[menu.main]]
        name = "Author"
        url = "https://armoghan-ul-mohmin.github.io/Portfolio/"
        weight = 3
    [[menu.main]]
        name = "Contact"
        url = "https://armoghan-ul-mohmin.github.io/Portfolio/Contact.html"
        weight = 4

[markup.goldmark.parser.attribute]
    block = true

# Don't touch this
[markup.goldmark.renderer]
    unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.91.2"