baseURL = "https://armoghan-ul-mohmin.github.io/Blogs/"
CanonifyURLs=true

languageCode = "en-us"


title = "Armoghan"
disqusShortname = "disqus-code"
googleAnalytics = "analytics-code"
pluralizeListTitles = false
enableemoji = false

[params]
    description = "A description for the meta tag of the site"
    # googleSearch = "google-search-code"
    showDate = true # make false if dont want to show date for evergeen articles
    math = false # best to enable this in the front matter of a page

    tagsInHome = 0     # set zero to not show in home page
    sectionsInHome = 0  # set zero to not show in home page
    paginatePostsPerPage = 10
    paginateTagsPerPage = 50

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "This Blog"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "All Tags"
                url = "/tags/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "All Posts"
                url = "/posts/"
                weight = 2
    [[menu.main]]
        name = "Notes"
        url = "/notes"
        weight = 3
    [[menu.main]]
        name = "Author"
        url = "https://armoghan-ul-mohmin.github.io/Portfolio/"
        weight = 4